# Funding options for Ground Zero Community
# Specify the ways people can support this project

github: [GroundZero-Community]
# patreon: GroundZeroDigital
# ko_fi: groundzero
# custom: ["https://groundzero.tech/support"]
