blank_issues_enabled: false
contact_links:
  - name: Discord Community Server
    url: https://discord.gg/4H2v6UwjmY
    about: Ask questions, get help, and chat with other members of the community.
  - name: Ground Zero Community Facebook Group
    url: https://www.facebook.com/groups/groundzerocommunity/
    about: Connect with other members and share your projects on Facebook.
