name: Markdown Linter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Install dependencies
      run: npm install

    - name: Run Markdown Lint
      run: npm run lint
